AllCops:
  TargetRubyVersion: 2.7.0
  NewCops: enable
  SuggestExtensions: true

Style/Documentation:
  Exclude:
    - spec/cattri/**/*.rb

Style/DocumentationMethod:
  Exclude:
    - spec/cattri/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - cattri.gemspec
    - spec/**/*.rb

Metrics/MethodLength:
  Max: 20
