module Cattri
  type identifier = ::String | ::Symbol

  type scope_types = :class | :instance

  type expose_types = :read_write | :read | :write | :none

  type visibility_types = :public | :protected | :private
end
